---
# Variables for Vault
catalog_find_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'catalog/find/vagrant', engine_mount_point='kv-applications') }}"
catalog_solr_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'catalog/solr/vagrant', engine_mount_point='kv-applications') }}"
dld_sidekiq_pro_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'sidekiq_pro', engine_mount_point='dld') }}"

docker_swarm_addr: "{{ ansible_host }}"

# Docker swarm setup vars
skip_repo: false
skip_containerd: false
skip_engine: false
skip_cli: false
skip_swarm: false
skip_group: false
skip_docker_py: false
skip_docker_compose: false

# expose the docker api (only for dev env) to allow IDE's to add remote interpreters for debugging
docker_daemon_config:
  hosts: ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
  default-ulimits:
    nofile:
      Name: "nofile"
      Hard: 1048576
      Soft: 1048576
docker_service_override: |
  [Service]
  ExecStart=
  ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock

os_dependencies:
  Alpine:
    - py3-jmespath
    - py3-pip
    - py3-setuptools
  Debian:
    - python3-jmespath
    - python3-pip
    - python3-setuptools
  RedHat:
    - python3-jmespath
    - python3-pip
    - python3-setuptools

pip_dependencies:
  - hvac
  - jsondiff
  - passlib
  - pyyaml
