---
roles:
  - name: docker-swarm
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/docker-swarm.git
    scm: git
    version: alpine

  - name: postgres
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/postgres.git
    scm: git
    version: main

  - name: redis
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/redis.git
    scm: git
    version: 1.2.1

  - name: solr
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/solr.git
    scm: git
    version: main