locations:
  offsite:
    - lippb10
    - athstorcir
    - stor
    - storcirc
    - storcrstxt
    - storm
  unavailable:
    - athNoCirc
    - storNoCirc
    - vpunavail
    - vanpNocirc
  pickup:
    Van Pelt Library:
      ils: VanPeltLib
      ill: Van Pelt Library
    Lockers at Van Pelt Library:
      ils: VPLOCKER
      ill: Lockers at Van Pelt
    Annenberg Library:
      ils: AnnenLib
      ill: Annenberg Library
    Athenaeum Library:
      ils: AthLib
    Holman Biotech Commons:
      ils: BiomLib
      ill: Biotech Commons
    Chemistry Library:
      ils: ChemLib
      ill: Chemistry Library
    Dental Medicine Library:
      ils: DentalLib
      ill: Dental Library
    Lockers at Dental Medicine Library:
      ils: DENTLOCKER
      ill: Lockers at Dental
    Fisher Fine Arts Library:
      ils: FisherFAL
      ill: Fine Arts Library
    Library at the Katz Center:
      ils: KatzLib
      ill: Katz Library
    Math/Physics/Astronomy Library:
      ils: MPALib
      ill: Math/Physics/Astronomy Library
    Museum Library:
      ils: MuseumLib
      ill: Museum Library
    Ormandy Music and Media Center:
      ils: MusicLib
    Pennsylvania Hospital Library - PAH Staff Only:
      ils: PAHospLib
      ill: PA Hospital Library
    Veterinary Library - New Bolton Center:
      ils: VetNBLib
      ill: New Bolton Center
    Veterinary Library - Penn Campus:
      ils: VetPennLib
      ill: Veterinary Library
  aeon_location_map:
    KislakCntr: KISLAK
    KatzLib: KATZ
    FisherFAL: FISHER
  aeon_sublocation_map:
    finecage: Fine Arts Cage
    finelock: Fine Locked Case
    finemaps: Fine Map Coll.
    finerare: Fine Rare Book
    fineraremp: Fine Rare Maps
    finerarept: Fine Rare Print
    cjsraram: RB Americana
    cjsambx: Arc Americana
    cjsmar: Margolis
    cjsrar: RB Room
    cjsspec: Special
    cjsths: Stacks Thesis
    cjsmemor: Memorial
    cjsrarfol: RB Folio
    cjsrarover: RB Oversize
    cjsrargiga: RB Giant
    cjsrarmini: RB Miniature
    cjsincun: RB Incunabula
    cjsrarms: RB Ms.
    cjsgf: Genizah
    cjsartif: Artifacts
    cjsarc: Arc Room
    cjsarcms: Arc Room Ms.
    cjsgrc: Arc Graphics
    cjsrarbx1: RB Box 1
    cjsrarbx2: RB Box 2
    cjsrarbx3: RB Box 3
    cjsrarbx4: RB Box 4
    cjsarcbox1: Arc Box 1
    cjsarcths: Arc Thesis
    cjshur: Hurowitz
    scsmith: Smith
    scfurn: Furness
    sclea: Lea
    scrare: RBC
    screfe: Reference
    sccurt: Curtis
    scdech: Dechert
    scelz: Elzevier
    scforr: Forrest
    scfoun: Founders
    scinc: Incunables
    scmss: Manuscripts
    scpspa: PSPA
    scsing: Singer-Mendenhall
    scteer: Teerink
    scyarn: Yarnall
    scwhit: Whitman
    newbrare: Fairman-Rogers
    storlimit: LIBRA Limited
    storrare: LIBRA Rare
    storspec: LIBRA Special
    scmst: Ms. Storage
    scfreed: Freedman
    scfast: Fast LIBRA
    scstor: RBC Storage
    sc1100c: 1100c LIBRA
    scsmithst: Smith Storage LIBRA
    scfurnst: Furness Storage LIBRA
    scdreis: Dreiser
    scelias: Swift Reading
    scbanks: Banks
    scparts: Books in Parts
    scdrey: Dreyfus
    scbyron: Byron
    sccomics: Comics
    scblank: Blank
    screfestor: Ref Storage
    screading: Reading Room Ref
    scgull: Gulliver
    scg123: scg123
    scmap: scmap
    scmsw: scmsw
    scdethou: De Thou
    sccanvas: Canvassing
    scvilain: Vilain-Wieck
    scschimmel: Schimmel
    sctehon: Tehon
    scadams: Adams
    scartbk: Artists
    musebrin: Museum Brinton
    muselock: Museum Locked
